[theme]
base = "dark"
primaryColor = "#e10600"
backgroundColor = "#000000"
secondaryBackgroundColor = "#15151e"
# textColor =
# redColor =
# orangeColor =
# yellowColor =
# blueColor =
# greenColor =
# violetColor =
# grayColor =
# redBackgroundColor =
# orangeBackgroundColor =
# yellowBackgroundColor =
# blueBackgroundColor =
# greenBackgroundColor =
# violetBackgroundColor =
# grayBackgroundColor =
# redTextColor =
# orangeTextColor =
# yellowTextColor =
# blueTextColor =
# greenTextColor =
# violetTextColor =
# grayTextColor =
# linkColor =
# linkUnderline =
# codeTextColor =
# codeBackgroundColor =
# font =
# fontFaces =
# baseFontSize =
# baseFontWeight =
# headingFont =
# headingFontSizes =
# headingFontWeights =
# codeFont =
# codeFontSize =
# codeFontWeight =
# baseRadius =
# buttonRadius =
borderColor = "#15151e"
dataframeBorderColor = "#15151e"
dataframeHeaderBackgroundColor = "#15151e"
# showWidgetBorder =
# showSidebarBorder =
# chartCategoricalColors = 
# chartSequentialColors =
# chartDivergingColors =